
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apartman_ann_development
  host: localhost
  username: app
  password: password

  
test:
  <<: *default
  database: apartman_ann_test
  host: localhost
  username: app
  password: password


production:
  <<: *default
  database: apartman_ann_production
  username: apartman_ann
  password: <%= ENV['APARTMAN_ANN_DATABASE_PASSWORD'] %>
